apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-idp-app
spec:
  rules:
  - host: python-idp-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-idp-app
            port:
              number: 8080
